#!/bin/bash

rm -rf ./ssh_id ./ssh_id.pub
docker build . -t apostrophe-dev || exit 1
docker rm --force dev || exit 1
# A named volume, not a bind mount, for better performance inside the container
docker create --name dev -v persistent:/persistent -p 3000:3000 -p 4045:445 apostrophe-dev || exit 1
