#!/bin/bash

# Make sure this exists in the persistent volume (Dockerfile is too early to see that)
mkdir -p /persistent/mongodb 

cat > /etc/samba/smb.conf <<EOM
[global]
  workgroup = SIMPLE
[persistent]
  comment = Reachable by host only
  path = /persistent
  read only = no
  force user = root
  unix extensions = yes
  vfs objects = fruit
EOM

echo -e "root\nroot" | smbpasswd -a root

# Services that fork on their own (TODO: this means they won't stop the container if they fail,
# but these are pretty stable)

/usr/sbin/smbd

# Services we'll monitor

m use stable --port 27017 --dbpath /persistent/mongodb &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?
