#!/bin/bash

# Make sure this exists in the persistent volume (Dockerfile is too early to see that)
mkdir -p /persistent/mongodb 

cat > /etc/ganesha/ganesha.conf <<EOM
EXPORT
{
        Export_Id = 2;
        Path = /persistent;
        Pseudo = /persistent;
        Protocols = 4;
        Access_Type = RW;
        Squash = None;
        FSAL
        {
                Name = VFS;
        }
}
EOM

# Services that fork on their own (TODO: this means they won't stop the container if they fail,
# but these are pretty stable)
/sbin/rpcbind
/usr/bin/ganesha.nfsd -C -N NIV_FULL_DEBUG -L /tmp/ganesha.log

m use stable --port 27017 --dbpath /persistent/mongodb &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?
